### ISSUE TITLE
Your contact details

### ISSUE THREAD

**Issue by mrpmorris** [ahass/YouML#2]
Hi Andre

Sorry to post this as an issue, but you don't have discussions enabled.

I'm wondering if I might be able to talk to you about a VS extension idea I am thinking of developing?

Could you email me, please?

mrpmorris@gmail.com

Thanks :)

**Comment by ahass** [comment]
Already sent my contact dedails... Wait for you.

**Comment by mrpmorris** [comment]
I can't find it. What did you write in the subject, so I can search for it?

**Comment by ahass** [comment]
12.12.2022

Subject: your mail

**Comment by mrpmorris** [comment]
I can't find it. Could you resend with the subject YouML, please?
